### ISSUE TITLE
Fix the Back / Next button tooltips

### ISSUE THREAD

**Issue by tanius** [gdpelican/edgeryders-form#4]
The mouse-over tooltips on the bottom-left "Back" and bottom-right "Next" button are a bit confusing right now :-)

* Slide 1 "Next" has tooltip "Ready" but Slide 2 "Back" also has tooltip "Back". Both of that should change because Slide 2 itself is called "Ready", not one of its neighboring slides.

* Both the "Back" and "Next" tooltips of all Slides Q… have tooltip "Q{{index}}". Looks like a templating bug, plus the "Back" button should use `index-1` rather than `index`.

* On the last slide the "Back" tooltip is "The last little bit!" but that only applies to the "Send" button, here replacing "Next".

**Comment by gdpelican** [comment]
I've made it so that the slides can provide custom 'backTitle' and 'nextTitle' attributes (with a default of 'Go Back' and 'Continue'), so it'll be easy to control this a lot or a little based on what gets put into the json file.

Before this goes out I'll tap up some documentation on how the json file works so it'll be easy to generate more forms (in whatever languages you choose), without having to write more code.
