### ISSUE TITLE
Fix remaining issues with the new language switcher

### ISSUE THREAD

**Issue by tanius** [gdpelican/edgeryders-form#8]
The new language switcher does not yet work for me :( I installed the most recent version on [bio26.edgeryders.eu](https://bio26.edgeryders.eu/) and did a clean build (`yarn install && yarn run build`) but so far, no language switcher appears.

There are two problems that I could identify:

* The `VUE_APP_LANG` parameter was removed in one of the last commits but is still needed in [`src/helpers/discourse.js` l. 3](https://github.com/gdpelican/edgeryders-form/blob/eea81a50a4bcd00f760f5892509a2f1d74341ce6/src/helpers/discourse.js#L3). So without the parameter present in `.env.production`, the application will not start (showing a "white screen of death").

* The English language strings are compiled into the resulting `dist/*` files by yarn, but not the Slovenian language strings. At least it appears that way from me doing `grep -R "Dobrodo" ./dist/*`.

**Comment by gdpelican** [comment]
I've pushed up a fix for discourse.js relying on VUE_APP_LANG (it doesn't anymore); I was hoping to wait on it (since we don't have SL-translated error messages yet anyhow), but hopefully that should fix it up.

A quick peek at the resultant `app.<fingerprint>.js` from `yarn run build` makes me think that the SL translations are getting included alright:
<img width="1319" alt="Captura de Pantalla 2019-11-08 a la(s) 13 22 33" src="https://user-images.githubusercontent.com/750477/68438996-e90c4980-022a-11ea-9663-874fcb90e955.png">

Let me know if that patches things up for you?

**Comment by tanius** [comment]
> Let me know if that patches things up for you?

Yes, both issues are gone now :-) (See [bio26.edgeryders.eu](https://bio26.edgeryders.eu/).)
